//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.03 at 11:26:04 AM CET 
//

package net.opengis.indoorgml.v_1_0.core;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import net.opengis.gml.v_3_2_1.AbstractFeatureMemberType;
import net.opengis.indoorgml.v_1_0.navigation.AnchorSpaceType;
import net.opengis.indoorgml.v_1_0.navigation.ConnectionSpaceType;
import net.opengis.indoorgml.v_1_0.navigation.GeneralSpaceType;
import net.opengis.indoorgml.v_1_0.navigation.NavigableSpaceType;
import net.opengis.indoorgml.v_1_0.navigation.TransferSpaceType;
import net.opengis.indoorgml.v_1_0.navigation.TransitionSpaceType;

/**
 * <p>
 * Java class for CellSpaceMemberType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CellSpaceMemberType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/gml/3.2}AbstractFeatureMemberType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element ref="{http://www.opengis.net/indoorgml/1.0/core}CellSpace"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.opengis.net/gml/3.2}AssociationAttributeGroup"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CellSpaceMemberType", propOrder = { "cellSpace" })
public class CellSpaceMemberType extends AbstractFeatureMemberType {

    @XmlElementRef(name = "CellSpace", namespace = "http://www.opengis.net/indoorgml/1.0/core", type = JAXBElement.class)
    protected JAXBElement<? extends CellSpaceType> cellSpace;
    @XmlAttribute
    protected List<String>                         nilReason;
    @XmlAttribute(namespace = "http://www.opengis.net/gml/3.2")
    @XmlSchemaType(name = "anyURI")
    protected String                               remoteSchema;
    @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
    protected String                               type;
    @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
    @XmlSchemaType(name = "anyURI")
    protected String                               href;
    @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
    @XmlSchemaType(name = "anyURI")
    protected String                               role;
    @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
    @XmlSchemaType(name = "anyURI")
    protected String                               arcrole;
    @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
    protected String                               title;
    @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
    protected String                               show;
    @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
    protected String                               actuate;

    /**
     * Gets the value of the cellSpace property.
     * 
     * @return possible object is {@link JAXBElement }{@code <}{@link CellSpaceType }{@code >} {@link JAXBElement }{@code <}{@link ConnectionSpaceType }{@code >} {@link JAXBElement }
     *         {@code <}{@link GeneralSpaceType }{@code >} {@link JAXBElement }{@code <}{@link NavigableSpaceType }{@code >} {@link JAXBElement }{@code <}{@link AnchorSpaceType }
     *         {@code >} {@link JAXBElement }{@code <}{@link TransitionSpaceType }{@code >} {@link JAXBElement }{@code <}{@link TransferSpaceType }{@code >}
     */
    public JAXBElement<? extends CellSpaceType> getCellSpace() {
        return cellSpace;
    }

    /**
     * Sets the value of the cellSpace property.
     * 
     * @param value
     *            allowed object is {@link JAXBElement }{@code <}{@link CellSpaceType }{@code >} {@link JAXBElement }{@code <}{@link ConnectionSpaceType }{@code >} {@link JAXBElement }
     *            {@code <}{@link GeneralSpaceType }{@code >} {@link JAXBElement }{@code <}{@link NavigableSpaceType }{@code >} {@link JAXBElement }{@code <}{@link AnchorSpaceType }
     *            {@code >} {@link JAXBElement }{@code <}{@link TransitionSpaceType }{@code >} {@link JAXBElement }{@code <}{@link TransferSpaceType }{@code >}
     */
    public void setCellSpace(JAXBElement<? extends CellSpaceType> value) {
        this.cellSpace = ((JAXBElement<? extends CellSpaceType>) value);
    }

    /**
     * Gets the value of the nilReason property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nilReason property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getNilReason().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link String }
     */
    public List<String> getNilReason() {
        if (nilReason == null) {
            nilReason = new ArrayList<String>();
        }
        return this.nilReason;
    }

    /**
     * Gets the value of the remoteSchema property.
     * 
     * @return possible object is {@link String }
     */
    public String getRemoteSchema() {
        return remoteSchema;
    }

    /**
     * Sets the value of the remoteSchema property.
     * 
     * @param value
     *            allowed object is {@link String }
     */
    public void setRemoteSchema(String value) {
        this.remoteSchema = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return possible object is {@link String }
     */
    public String getType() {
        if (type == null) {
            return "simple";
        } else {
            return type;
        }
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *            allowed object is {@link String }
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the href property.
     * 
     * @return possible object is {@link String }
     */
    public String getHref() {
        return href;
    }

    /**
     * Sets the value of the href property.
     * 
     * @param value
     *            allowed object is {@link String }
     */
    public void setHref(String value) {
        this.href = value;
    }

    /**
     * Gets the value of the role property.
     * 
     * @return possible object is {@link String }
     */
    public String getRole() {
        return role;
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *            allowed object is {@link String }
     */
    public void setRole(String value) {
        this.role = value;
    }

    /**
     * Gets the value of the arcrole property.
     * 
     * @return possible object is {@link String }
     */
    public String getArcrole() {
        return arcrole;
    }

    /**
     * Sets the value of the arcrole property.
     * 
     * @param value
     *            allowed object is {@link String }
     */
    public void setArcrole(String value) {
        this.arcrole = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return possible object is {@link String }
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *            allowed object is {@link String }
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the show property.
     * 
     * @return possible object is {@link String }
     */
    public String getShow() {
        return show;
    }

    /**
     * Sets the value of the show property.
     * 
     * @param value
     *            allowed object is {@link String }
     */
    public void setShow(String value) {
        this.show = value;
    }

    /**
     * Gets the value of the actuate property.
     * 
     * @return possible object is {@link String }
     */
    public String getActuate() {
        return actuate;
    }

    /**
     * Sets the value of the actuate property.
     * 
     * @param value
     *            allowed object is {@link String }
     */
    public void setActuate(String value) {
        this.actuate = value;
    }

    
    /*
     * (non-Javadoc)
     * @see org.jvnet.jaxb2_commons.lang.CopyTo#createNewInstance()
     */
    @Override
    public Object createNewInstance() {
        return new CellSpaceMemberType();
    }

}
