//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.03 at 11:26:04 AM CET 
//

package net.opengis.indoorgml.v_1_0.core;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import net.opengis.gml.v_3_2_1.AbstractFeatureType;
import net.opengis.gml.v_3_2_1.SolidPropertyType;
import net.opengis.gml.v_3_2_1.SurfacePropertyType;
import net.opengis.indoorgml.v_1_0.navigation.NavigableSpaceType;

/**
 * <p>
 * Java class for CellSpaceType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CellSpaceType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/gml/3.2}AbstractFeatureType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.opengis.net/indoorgml/1.0/core}CellSpaceGeometry" minOccurs="0"/>
 *         &lt;element name="duality" type="{http://www.opengis.net/indoorgml/1.0/core}StatePropertyType" minOccurs="0"/>
 *         &lt;element name="externalReference" type="{http://www.opengis.net/indoorgml/1.0/core}ExternalReferenceType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="partialboundedBy" type="{http://www.opengis.net/indoorgml/1.0/core}CellSpaceBoundaryPropertyType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CellSpaceType", propOrder = { "geometry3D", "geometry2D", "duality", "externalReference", "partialboundedBy" })
@XmlSeeAlso({ NavigableSpaceType.class })
public class CellSpaceType extends AbstractFeatureType {

    @XmlElement(name = "Geometry3D")
    protected SolidPropertyType                   geometry3D;
    @XmlElement(name = "Geometry2D")
    protected SurfacePropertyType                 geometry2D;
    protected StatePropertyType                   duality;
    protected List<ExternalReferenceType>         externalReference;
    protected List<CellSpaceBoundaryPropertyType> partialboundedBy;

    /**
     * Gets the value of the geometry3D property.
     * 
     * @return possible object is {@link SolidPropertyType }
     */
    public SolidPropertyType getGeometry3D() {
        return geometry3D;
    }

    /**
     * Sets the value of the geometry3D property.
     * 
     * @param value
     *            allowed object is {@link SolidPropertyType }
     */
    public void setGeometry3D(SolidPropertyType value) {
        this.geometry3D = value;
    }

    /**
     * Gets the value of the geometry2D property.
     * 
     * @return possible object is {@link SurfacePropertyType }
     */
    public SurfacePropertyType getGeometry2D() {
        return geometry2D;
    }

    /**
     * Sets the value of the geometry2D property.
     * 
     * @param value
     *            allowed object is {@link SurfacePropertyType }
     */
    public void setGeometry2D(SurfacePropertyType value) {
        this.geometry2D = value;
    }

    /**
     * Gets the value of the duality property.
     * 
     * @return possible object is {@link StatePropertyType }
     */
    public StatePropertyType getDuality() {
        return duality;
    }

    /**
     * Sets the value of the duality property.
     * 
     * @param value
     *            allowed object is {@link StatePropertyType }
     */
    public void setDuality(StatePropertyType value) {
        this.duality = value;
    }

    /**
     * Gets the value of the externalReference property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the externalReference property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getExternalReference().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link ExternalReferenceType }
     */
    public List<ExternalReferenceType> getExternalReference() {
        if (externalReference == null) {
            externalReference = new ArrayList<ExternalReferenceType>();
        }
        return this.externalReference;
    }

    /**
     * Gets the value of the partialboundedBy property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the partialboundedBy property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getPartialboundedBy().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link CellSpaceBoundaryPropertyType }
     */
    public List<CellSpaceBoundaryPropertyType> getPartialboundedBy() {
        if (partialboundedBy == null) {
            partialboundedBy = new ArrayList<CellSpaceBoundaryPropertyType>();
        }
        return this.partialboundedBy;
    }

    /*
     * (non-Javadoc)
     * @see org.jvnet.jaxb2_commons.lang.CopyTo#createNewInstance()
     */
    @Override
    public Object createNewInstance() {
        return new CellSpaceType();
    }

}
