//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.03 at 11:26:04 AM CET 
//

package net.opengis.indoorgml.v_1_0.core;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import net.opengis.gml.v_3_2_1.AbstractFeatureType;

/**
 * <p>
 * Java class for IndoorFeaturesType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IndoorFeaturesType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/gml/3.2}AbstractFeatureType">
 *       &lt;sequence>
 *         &lt;element name="primalSpaceFeatures" type="{http://www.opengis.net/indoorgml/1.0/core}PrimalSpaceFeaturesPropertyType" minOccurs="0"/>
 *         &lt;element ref="{http://www.opengis.net/indoorgml/1.0/core}MultiLayeredGraph"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IndoorFeatures", propOrder = { "primalSpaceFeatures", "multiLayeredGraph" })
@XmlRootElement(name = "IndoorFeatures")
public class IndoorFeaturesType extends AbstractFeatureType {

    protected PrimalSpaceFeaturesPropertyType primalSpaceFeatures;
    @XmlElement(name = "MultiLayeredGraph", required = true)
    protected MultiLayeredGraphType           multiLayeredGraph;

    /**
     * Gets the value of the primalSpaceFeatures property.
     * 
     * @return possible object is {@link PrimalSpaceFeaturesPropertyType }
     */
    public PrimalSpaceFeaturesPropertyType getPrimalSpaceFeatures() {
        return primalSpaceFeatures;
    }

    /**
     * Sets the value of the primalSpaceFeatures property.
     * 
     * @param value
     *            allowed object is {@link PrimalSpaceFeaturesPropertyType }
     */
    public void setPrimalSpaceFeatures(PrimalSpaceFeaturesPropertyType value) {
        this.primalSpaceFeatures = value;
    }

    /**
     * Gets the value of the multiLayeredGraph property.
     * 
     * @return possible object is {@link MultiLayeredGraphType }
     */
    public MultiLayeredGraphType getMultiLayeredGraph() {
        return multiLayeredGraph;
    }

    /**
     * Sets the value of the multiLayeredGraph property.
     * 
     * @param value
     *            allowed object is {@link MultiLayeredGraphType }
     */
    public void setMultiLayeredGraph(MultiLayeredGraphType value) {
        this.multiLayeredGraph = value;
    }

    /*
     * (non-Javadoc)
     * @see org.jvnet.jaxb2_commons.lang.CopyTo#createNewInstance()
     */
    @Override
    public Object createNewInstance() {
        return new IndoorFeaturesType();
    }

}
