//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.03 at 11:26:04 AM CET 
//


package net.opengis.indoorgml.v_1_0.core;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SpaceLayerClassTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SpaceLayerClassTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="TOPOGRAPHIC"/>
 *     &lt;enumeration value="SENSOR"/>
 *     &lt;enumeration value="LOGICAL"/>
 *     &lt;enumeration value="TAGS"/>
 *     &lt;enumeration value="LOGICAL"/>
 *     &lt;enumeration value="UNKNOWN"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SpaceLayerClassTypeType")
@XmlEnum
public enum SpaceLayerClassTypeType {

    TOPOGRAPHIC,
    SENSOR,
    LOGICAL,
    TAGS,
    UNKNOWN;

    public String value() {
        return name();
    }

    public static SpaceLayerClassTypeType fromValue(String v) {
        return valueOf(v);
    }

}
