//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.03 at 11:26:04 AM CET 
//

package net.opengis.indoorgml.v_1_0.core;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import net.opengis.gml.v_3_2_1.AbstractFeatureType;
import net.opengis.gml.v_3_2_1.CodeType;

/**
 * <p>
 * Java class for SpaceLayerType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpaceLayerType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/gml/3.2}AbstractFeatureType">
 *       &lt;sequence>
 *         &lt;element name="usage" type="{http://www.opengis.net/gml/3.2}CodeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="terminationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="function" type="{http://www.opengis.net/gml/3.2}CodeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="creationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="class" type="{http://www.opengis.net/indoorgml/1.0/core}SpaceLayerClassTypeType" minOccurs="0"/>
 *         &lt;element name="nodes" type="{http://www.opengis.net/indoorgml/1.0/core}NodesType" maxOccurs="unbounded"/>
 *         &lt;element name="edges" type="{http://www.opengis.net/indoorgml/1.0/core}EdgesType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpaceLayerType", propOrder = { "usage", "terminationDate", "function", "creationDate", "clazz", "nodes", "edges" })
public class SpaceLayerType extends AbstractFeatureType {

    protected List<CodeType>          usage;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar    terminationDate;
    protected List<CodeType>          function;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar    creationDate;
    @XmlElement(name = "class")
    protected SpaceLayerClassTypeType clazz;
    @XmlElement(required = true)
    protected List<NodesType>         nodes;
    protected List<EdgesType>         edges;

    /**
     * Gets the value of the usage property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the usage property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getUsage().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link CodeType }
     */
    public List<CodeType> getUsage() {
        if (usage == null) {
            usage = new ArrayList<CodeType>();
        }
        return this.usage;
    }

    /**
     * Gets the value of the terminationDate property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getTerminationDate() {
        return terminationDate;
    }

    /**
     * Sets the value of the terminationDate property.
     * 
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     */
    public void setTerminationDate(XMLGregorianCalendar value) {
        this.terminationDate = value;
    }

    /**
     * Gets the value of the function property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the function property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getFunction().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link CodeType }
     */
    public List<CodeType> getFunction() {
        if (function == null) {
            function = new ArrayList<CodeType>();
        }
        return this.function;
    }

    /**
     * Gets the value of the creationDate property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getCreationDate() {
        return creationDate;
    }

    /**
     * Sets the value of the creationDate property.
     * 
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     */
    public void setCreationDate(XMLGregorianCalendar value) {
        this.creationDate = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * @return possible object is {@link SpaceLayerClassTypeType }
     */
    public SpaceLayerClassTypeType getClazz() {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *            allowed object is {@link SpaceLayerClassTypeType }
     */
    public void setClazz(SpaceLayerClassTypeType value) {
        this.clazz = value;
    }

    /**
     * Gets the value of the nodes property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nodes property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getNodes().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link NodesType }
     */
    public List<NodesType> getNodes() {
        if (nodes == null) {
            nodes = new ArrayList<NodesType>();
        }
        return this.nodes;
    }

    /**
     * Gets the value of the edges property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the edges property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getEdges().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link EdgesType }
     */
    public List<EdgesType> getEdges() {
        if (edges == null) {
            edges = new ArrayList<EdgesType>();
        }
        return this.edges;
    }

    /*
     * (non-Javadoc)
     * @see org.jvnet.jaxb2_commons.lang.CopyTo#createNewInstance()
     */
    @Override
    public Object createNewInstance() {
        return new SpaceLayerType();
    }
}
