//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.03 at 11:26:04 AM CET 
//


package net.opengis.indoorgml.v_1_0.navigation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import net.opengis.indoorgml.v_1_0.core.CellSpaceBoundaryType;


/**
 * <p>Java class for NavigableBoundaryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NavigableBoundaryType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/indoorgml/1.0/core}CellSpaceBoundaryType">
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NavigableBoundaryType")
@XmlSeeAlso({
    TransferBoundaryType.class
})
public class NavigableBoundaryType
    extends CellSpaceBoundaryType
{


}
