//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.03 at 11:26:04 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.opengis.net/indoorgml/1.0/navigation", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package net.opengis.indoorgml.v_1_0.navigation;
