//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.03 at 11:26:04 AM CET 
//

package net.opengis.indoorgml.v_1_0.navigation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import net.opengis.gml.v_3_2_1.AbstractFeatureType;

/**
 * <p>
 * Java class for RouteType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RouteType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/gml/3.2}AbstractFeatureType">
 *       &lt;sequence>
 *         &lt;element name="startRouteNode" type="{http://www.opengis.net/indoorgml/1.0/navigation}RouteNodePropertyType"/>
 *         &lt;element name="endRouteNode" type="{http://www.opengis.net/indoorgml/1.0/navigation}RouteNodePropertyType"/>
 *         &lt;element name="routeNodes" type="{http://www.opengis.net/indoorgml/1.0/navigation}RouteNodesType"/>
 *         &lt;element name="path" type="{http://www.opengis.net/indoorgml/1.0/navigation}PathType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RouteType", propOrder = { "startRouteNode", "endRouteNode", "routeNodes", "path" })
public class RouteType extends AbstractFeatureType {

    @XmlElement(required = true)
    protected RouteNodePropertyType startRouteNode;
    @XmlElement(required = true)
    protected RouteNodePropertyType endRouteNode;
    @XmlElement(required = true)
    protected RouteNodesType        routeNodes;
    @XmlElement(required = true)
    protected PathType              path;

    /**
     * Gets the value of the startRouteNode property.
     * 
     * @return possible object is {@link RouteNodePropertyType }
     */
    public RouteNodePropertyType getStartRouteNode() {
        return startRouteNode;
    }

    /**
     * Sets the value of the startRouteNode property.
     * 
     * @param value
     *            allowed object is {@link RouteNodePropertyType }
     */
    public void setStartRouteNode(RouteNodePropertyType value) {
        this.startRouteNode = value;
    }

    /**
     * Gets the value of the endRouteNode property.
     * 
     * @return possible object is {@link RouteNodePropertyType }
     */
    public RouteNodePropertyType getEndRouteNode() {
        return endRouteNode;
    }

    /**
     * Sets the value of the endRouteNode property.
     * 
     * @param value
     *            allowed object is {@link RouteNodePropertyType }
     */
    public void setEndRouteNode(RouteNodePropertyType value) {
        this.endRouteNode = value;
    }

    /**
     * Gets the value of the routeNodes property.
     * 
     * @return possible object is {@link RouteNodesType }
     */
    public RouteNodesType getRouteNodes() {
        return routeNodes;
    }

    /**
     * Sets the value of the routeNodes property.
     * 
     * @param value
     *            allowed object is {@link RouteNodesType }
     */
    public void setRouteNodes(RouteNodesType value) {
        this.routeNodes = value;
    }

    /**
     * Gets the value of the path property.
     * 
     * @return possible object is {@link PathType }
     */
    public PathType getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *            allowed object is {@link PathType }
     */
    public void setPath(PathType value) {
        this.path = value;
    }

    /*
     * (non-Javadoc)
     * @see org.jvnet.jaxb2_commons.lang.CopyTo#createNewInstance()
     */
    @Override
    public Object createNewInstance() {
        return new RouteType();
    }

}
