//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.03 at 11:26:04 AM CET 
//

package net.opengis.indoorgml.v_1_0.navigation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import net.opengis.gml.v_3_2_1.AbstractFeatureMemberType;

/**
 * <p>
 * Java class for RouteNodeMemberType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RouteNodeMemberType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/gml/3.2}AbstractFeatureMemberType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opengis.net/indoorgml/1.0/navigation}RouteNode"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RouteNodeMemberType", propOrder = { "routeNode" })
public class RouteNodeMemberType extends AbstractFeatureMemberType {

    @XmlElement(name = "RouteNode", required = true)
    protected RouteNodeType routeNode;

    /**
     * Gets the value of the routeNode property.
     * 
     * @return possible object is {@link RouteNodeType }
     */
    public RouteNodeType getRouteNode() {
        return routeNode;
    }

    /**
     * Sets the value of the routeNode property.
     * 
     * @param value
     *            allowed object is {@link RouteNodeType }
     */
    public void setRouteNode(RouteNodeType value) {
        this.routeNode = value;
    }

    /*
     * (non-Javadoc)
     * @see org.jvnet.jaxb2_commons.lang.CopyTo#createNewInstance()
     */
    @Override
    public Object createNewInstance() {
        return new RouteNodeMemberType();
    }
}
