//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.03 at 11:26:04 AM CET 
//

package net.opengis.indoorgml.v_1_0.navigation;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import net.opengis.gml.v_3_2_1.AbstractFeatureType;
import net.opengis.gml.v_3_2_1.CurvePropertyType;
import net.opengis.indoorgml.v_1_0.core.TransitionPropertyType;

/**
 * <p>
 * Java class for RouteSegmentType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RouteSegmentType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/gml/3.2}AbstractFeatureType">
 *       &lt;sequence>
 *         &lt;element name="weight" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="connects" type="{http://www.opengis.net/indoorgml/1.0/navigation}RouteNodePropertyType" maxOccurs="2" minOccurs="2"/>
 *         &lt;element name="referencedTransition" type="{http://www.opengis.net/indoorgml/1.0/core}TransitionPropertyType"/>
 *         &lt;element name="geometry" type="{http://www.opengis.net/gml/3.2}CurvePropertyType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RouteSegmentType", propOrder = { "weight", "connects", "referencedTransition", "geometry" })
public class RouteSegmentType extends AbstractFeatureType {

    protected double                      weight;
    @XmlElement(required = true)
    protected List<RouteNodePropertyType> connects;
    @XmlElement(required = true)
    protected TransitionPropertyType      referencedTransition;
    @XmlElement(required = true)
    protected CurvePropertyType           geometry;

    /**
     * Gets the value of the weight property.
     */
    public double getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     */
    public void setWeight(double value) {
        this.weight = value;
    }

    /**
     * Gets the value of the connects property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the connects property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getConnects().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link RouteNodePropertyType }
     */
    public List<RouteNodePropertyType> getConnects() {
        if (connects == null) {
            connects = new ArrayList<RouteNodePropertyType>();
        }
        return this.connects;
    }

    /**
     * Gets the value of the referencedTransition property.
     * 
     * @return possible object is {@link TransitionPropertyType }
     */
    public TransitionPropertyType getReferencedTransition() {
        return referencedTransition;
    }

    /**
     * Sets the value of the referencedTransition property.
     * 
     * @param value
     *            allowed object is {@link TransitionPropertyType }
     */
    public void setReferencedTransition(TransitionPropertyType value) {
        this.referencedTransition = value;
    }

    /**
     * Gets the value of the geometry property.
     * 
     * @return possible object is {@link CurvePropertyType }
     */
    public CurvePropertyType getGeometry() {
        return geometry;
    }

    /**
     * Sets the value of the geometry property.
     * 
     * @param value
     *            allowed object is {@link CurvePropertyType }
     */
    public void setGeometry(CurvePropertyType value) {
        this.geometry = value;
    }

    /*
     * (non-Javadoc)
     * @see org.jvnet.jaxb2_commons.lang.CopyTo#createNewInstance()
     */
    @Override
    public Object createNewInstance() {
        return new RouteSegmentType();
    }

}
